### Ćwiczenie 1 

In [3]:
import random 
import numpy as np
# 1. Przygotować wektor wertykalny (A) zawierający 10 argumentów z przedziału 1:20 (array(10,0)).
A = np.random.randint(1,20,size=(10,1))
print(A)

[[ 6]
 [ 9]
 [ 1]
 [ 1]
 [13]
 [16]
 [ 4]
 [11]
 [14]
 [ 9]]


In [6]:
#2. Przygotować wektor wertykalny (B) zawierający 10 argumentów z przedziału 0:1 (array(10,0)).
B = np.random.rand(10,1)
print(B)

[[0.61860287]
 [0.35196911]
 [0.61144606]
 [0.08714585]
 [0.01551781]
 [0.59369204]
 [0.4853269 ]
 [0.39259084]
 [0.06529093]
 [0.86071525]]


In [7]:
#3. Wykonać mnożenie dwóch wektorów A i B.
print(A*B)

[[3.71161721]
 [3.16772203]
 [0.61144606]
 [0.08714585]
 [0.20173158]
 [9.49907257]
 [1.94130762]
 [4.31849919]
 [0.91407303]
 [7.74643724]]


In [8]:

#4. Następnie wykonać mnożenie skalarne wektora A oraz c = 2.
print(2 * A) 

[[12]
 [18]
 [ 2]
 [ 2]
 [26]
 [32]
 [ 8]
 [22]
 [28]
 [18]]


In [10]:
#5. Stworzyć macierz 4x4 (W), w których argumenty powinny być losowymi liczbami
#całkowitymi o wartościach z przedziału 1:100. Czy typ ndarray i matrix w pythonie to
#to samo?
W = np.random.randint(1,100,size=(4,4))
print(W)

[[50 45 27 49]
 [57 81 16 26]
 [28 44 30 81]
 [55 95 62 53]]


In [12]:
#6. Wyznaczyć przekątną macierzy.
print(np.diagonal(W))

[50 81 30 53]


In [13]:
#7. Przeprowadzić transponowanie macierzy ‘na piechotę’.
rez = [[W[j][i] for j in range(len(W))] for i in range(len(W[0]))]
transpozed_matrix = [row for row in rez]
print(np.array(transpozed_matrix))

[[50 57 28 55]
 [45 81 44 95]
 [27 16 30 62]
 [49 26 81 53]]
